name: GitHub Actions Build and Deploy Demo
on:
	push:
		branches:
			- master
jobs:
	build-and-deploy:
		runs-on: ubuntu-latest
		steeps:
			- name: Checkout
				uses: actions/checkout@master
			- name: Build and deploy
				uses: jamesIves/github-pages-deploy-actions@master
				env:
					ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
					BRANCH: master
					FOLDER: dist
					BUILD_SCRIPT: npm install && npm run build

# https://github.com/marketplace/actions/deploy-to-github-pages